GEE_SERVICE_ACCOUNT = "streamlit-gee-app@second-seeker-450217-k1.iam.gserviceaccount.com"

GEE_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCx2M0+gRuOPoRF
XNbKwRYxGiIvxtrGlxRPpo9BgDwhJDl4+M36fMBHCUeZs5pCLMLuOCJDq2YZw750
U6EY9lF6/xFISc7hUWgzTr1DuVeFtQK+qgFdP9uPUKkKQXU4Zg0/yGwY45coeKbg
uZ0s3XJFORjaUGI/x0giperH6+Ksg8MpAyOSqMG+v9oa4/QJOFXCTrmIihT/vIav
+G6nxAfxJPYioWpPRQ01m6YTAykpIMfYgx/vybla9T2/NF91TscdJF/N3926n0fT
FmnE0Qx/8oyYjX7TX3ZxrTv7/jv3dR4jl9KBJVG+dsFCeqUKzTQb8WpmmJsg2kPa
qMrOrwTzAgMBAAECgf8aZhQRMxjkBGOd6Cn57q9cmoR4kwvmboaVTCP3lRFX2git
7ECm7d2crcPzDLXZHMvSkIKFiOue529d1QwUqHtvxmzKTipnR64v74AojVpwfm3p
31JUhSYSH+b3nr/Hn15YGWfySdYmK8KZmPO7tSNBIziNL2FmFi6e9gHjqx/6e1UQ
A0eDA7fxUnPAk+LlFy+4qOHvA6+ZnFXdBQBOAgY4jjToY68OcrP91Fq6GpQaLYU9
zAejFaEyN5JLajAUbaKCqCZDnMmb4KHTaLdiNBOYF+VvanjEsjLmlELGNUSfHhrj
xypnMhfWhCtVrkZC+sauZQkLDL7CAbWbpufFYWECgYEA4E9rmde6eGNhZxvQnjJ6
WKJrznXjdfmRQDDAYHbUeDr+C+eR+TgyPZksACLbpy2c88NAkZVGr1dMJ6F12boX
0rjs8K+WkTPOeq8ygvDS5fDQzb681Qb0Ure+96sZZdXWG+nAA+kjDJpdF04yOCaR
yKrkSqibu/kPgTfdaKX223sCgYEAyvjzjO7YhkbihrTE7ZpELYy2bc/6BqyXf+9a
pvQ+L9qqxWzwgkwUblV6ypw5qQPkr5MfC23zxMFTEqtPe6mXMW+5ucGTDmdjY1mB
7vY3rqjvSMOAcqmahMIpz2iuqB8F5zqhigFdPi137lOb5orxD2kp+xu67ezVFhLi
3083JukCgYAi/WCMg/FLfD0iZ11YgAlDsDpe31bW/VIiEDjCE2c7RgCA/ONxW8nC
gBU0BDv9TQkxoSB+VSnMijKP8AjBKN00erJDLTCwf8NSseeQM17CjZkUrw8nr8kG
6jC405DHqN6YRhM0yPY1rhKdYw5EYgfVpIqt9rUsUkKP5pX8D/985wKBgDjxUtKN
B23UYSTNfhnyl4H34g44tLo+nVok+lewWenu/M3aXDcRxQGXNZW18m86SmP/cEwy
kpr2aanpKalV0Lbr0z0L04fM9ZMfv1Yc+U4k0sylHFoOvuzT1Ar+IVHFMlDGoB8p
dtFEzEquZiRtgmeCZ2atRuoM8VL6BXAEt0JRAoGAUHq7Ln321q26U6XYD3P9C7Ty
IVGSR4jRoAeIdugXnP1B12WosOgk2cNcM7vZZ/mj6ATjCctzmempxzsCPKsDI78O
22y0K1PvMA2SNf1EPO9gerBs56VOolXLTUY4vSOQ80z3H6Gx7ATF3WLPtA5OsZmC
Gq8jpFd/wEcvoWuv/rc=
-----END PRIVATE KEY-----
"""
